name: cs7641_2
channels:
  - conda-forge
  - defaults
dependencies:
  - blas
  - ca-certificates
  - certifi
  - cycler
  - dbus
  - expat
  - fontconfig
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - intel-openmp
  - jpeg
  - kiwisolver
  - kneed
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libstdcxx-ng
  - libuuid
  - libxcb
  - libxml2
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy
  - numpy-base
  - openssl
  - pandas
  - patsy
  - pcre
  - pip
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - qt
  - readline
  - scikit-learn
  - scikit-optimize
  - scipy
  - seaborn
  - setuptools
  - sip
  - six
  - sqlite
  - statsmodels
  - tk
  - tornado
  - wheel
  - xlrd
  - xz
  - zlib


